import type { ReactNode } from "react";
// These styles apply to every route in the application
import "./globals.css";

export const metadata = {
  title: "My Next App",
  description: "Generated by me",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const res = await fetch("https://api.github.com/repos/vercel/next.js");

  const data = await res.json();

  // console.log("data: ", data);

  return (
    <html lang="en">
      <body>
        <h1 className="text-4xl font-bold underline">{data.id}</h1>
        {children}
      </body>
    </html>
  );
}
